"""Update the pitch model

Revision ID: 38c916975e81
Revises: 75bf89e5d9d7
Create Date: 2021-04-24 23:38:53.477993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c916975e81'
down_revision = '75bf89e5d9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitch', sa.Column('category', sa.String(), nullable=True))
    op.add_column('pitch', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('pitch', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'description')
    op.drop_column('pitch', 'category')
    op.drop_table('comment')
    op.drop_table('category')
    # ### end Alembic commands ###
